### ISSUE TITLE
<C-j> works but <C-k> doesn't when navigating the yank list

### ISSUE THREAD

**Issue by blasco** [neoclide/coc-yank#11]
I can navigate down with `<c-j>` but I cannot go up with `<c-k>`. This works in other coc-lists, it only happens in coc-yank that I trigger with `<space>y` as suggested.

**Comment by chemzqm** [comment]
I can't reproduce.

**Comment by chemzqm** [comment]
Closing unless you can provide minimal vimrc to reproduce

**Comment by chemzqm** [comment]
The suggested command start CocList on normal mode, use normal command to navigate.

**Comment by blasco** [comment]
You are right, that was the issue.
