### ISSUE TITLE
Highlighting color doesn't change

### ISSUE THREAD

**Issue by blasco** [neoclide/coc-yank#12]
I've updated the color as suggested:

```
hi HighlightedyankRegion gui=NONE guibg=#13354A term=NONE ctermbg=0
```

But this doesn't take any effect

**Comment by chemzqm** [comment]
I can't reproduce.

**Comment by chemzqm** [comment]
Closing unless you can provide minimal vimrc to reproduce.
You can try that command in your vim's command line.

**Comment by blasco** [comment]
It doesn't work. This fixes the issue:
```
autocmd VimEnter * execute "hi HighlightedyankRegion gui=NONE guibg=White term=NONE ctermbg=0"
```

**Comment by chemzqm** [comment]
It's because your colorsheme overwrite your custom highlight.
