### ISSUE TITLE
Any visually selected text goes to the yank history

### ISSUE THREAD

**Issue by blasco** [neoclide/coc-yank#14]
Any visual selection seems to go to the yank history. It doesn't go to the vim yank registers, but it goes to coc-yanks history. Is there a way to disable this?

**Comment by blasco** [comment]
For anyone having issues, switching to neovim fixes everything.

**Comment by chemzqm** [comment]
Can't reproduce on vim8

**Comment by AtomToast** [comment]
This is a feature that iirc you can enable in vim but that is currently broken in neovim. https://github.com/neovim/neovim/issues/2325 
You probably enable this functionality somewhere in your vimrc
