### ISSUE TITLE
How to delete a yank?

### ISSUE THREAD

**Issue by luisgomez-wk** [neoclide/coc-yank#16]
I tried looking for the file which yanks are stored in and couldn't find it

`:CocCommand yank.clean` worked to clear all yanks, but what if i just wanted to delete the one?

**Comment by fannheyward** [comment]
`:CocList yank` list all yanks, and `tab` to open actions list. You can `d` to delete a yank.

**Comment by luisgomez-wk** [comment]
When I do that it starts fuzzy searching the list (because of my `fzf` installation)

Is there an easy way to tell which file yanks are stored in?

**Comment by fannheyward** [comment]
All yanks are store in `/.config/coc/extensions/coc-yank-data/yank` file.
