### ISSUE TITLE
“yank.highlight.enable"和“set guioptions+=a”有冲突

### ISSUE THREAD

**Issue by imbear** [neoclide/coc-yank#18]
之前在coc.nvim上提过这个问题
neoclide/coc.nvim#1411

现在看来是这两个设置起了冲突

**Comment by chemzqm** [comment]
Use `"yank.highlight.enable": false` in your coc-settings.json.

**Comment by hujianxin** [comment]
可以稳定复现这个问题，请问只能关掉highlight吗？

**Comment by chemzqm** [comment]
vim 的 bug

**Comment by hujianxin** [comment]
了解了，多谢
