### ISSUE TITLE
Opening Yank list changes vim cursor

### ISSUE THREAD

**Issue by Daniel-M** [neoclide/coc-yank#20]
Hello, I've rencently installed coc-yank following the readme. Whenever I use the keymap that shows the yank history, the cursor changes permanently from the usual rectangular white cursor to a line | unless I close and open a new instance of Neovim. Just like in the following images,

Before opening yank list:
![image](https://user-images.githubusercontent.com/669787/75828282-7b57d080-5d79-11ea-81db-d5db1fdda842.png)

Just after closing the yank list:
![image](https://user-images.githubusercontent.com/669787/75828383-b954f480-5d79-11ea-8f10-f488547fee54.png)

Is not a critical bug, it is more like an annoyance since I lose the context of my editing, traced this behaviour down to this extension and I can provide more information upon request

**Comment by chemzqm** [comment]
Please provide your `:CocInfo` and result of  `echo &guicursor`

**Comment by Daniel-M** [comment]
Sure,
`:CocInfo`
```
## versions

vim version: NVIM v0.4.3
node version: v10.15.3
coc.nvim version: 0.0.75-89c0c2380b
term: xterm-256color
platform: linux

## Messages

## Output channel: snippets


## Output channel: highlight

[Info  - 07:34:56] Highlight server running in node v10.15.3
```

`echo &guicursor` shows both before and after opening the list the same value `a:blinkon100`

Coudl it be a conflict with another plugin?

**Comment by chemzqm** [comment]
It's bug of neovim, should be fixed on master of coc.nvim now.

**Comment by Daniel-M** [comment]
@chemzqm thank you
