### ISSUE TITLE
Long delay before highlight shows up with `yy`

### ISSUE THREAD

**Issue by DomKennedy** [neoclide/coc-yank#22]
If I yank with `yy`, there seems to be a delay of over a full second before it shows up. By contrast, other yank motions (`Y`, `yj`, `yip`) display a highlight pretty much instantly.

Also, if I do `yyp` or `yyP` to yank and then immediately paste a line, the highlight seems to show up on the new, pasted line, rather than the original line. Obviously the content of the two lines is identical, but this seems unexpected.

I've experienced this on both macOS natively, and Ubuntu over SSH.

My `init.vim`, for reference:

<details>
" plugins

call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'machakann/vim-sandwich'
Plug 'gaving/vim-textobj-argument'
Plug 'wellle/targets.vim'
Plug 'AndrewRadev/dsf.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'sbdchd/neoformat'
Plug 'tpope/vim-sensible'
Plug 'terryma/vim-multiple-cursors'
Plug 'bkad/CamelCaseMotion'

call plug#end()

" Run black on save
let g:neoformat_enabled_python = ['black']
augroup fmt
  autocmd!
  autocmd BufWritePre * undojoin | Neoformat
augroup ENDo

" Ctrl+P to start FZF
noremap <C-p> :FZF<CR>

" jk to leave insert mode
inoremap jk <Esc>

" Ecs clears search highlighting
nnoremap <Esc> :noh<CR><Esc>

" Use main clipboard by default (not working; #TODO)
set clipboard=unnamedplus

" Blinking cursor
set guicursor=a:blinkon100

" Line numbers
set number
set relativenumber

" Ctrl+Backspace in insert mode (not working; #TODO)
inoremap <M-BS> <C-W>
set backspace=indent,eol,start

" c = iw textobject
onoremap c iw
onoremap C iW

" id = subword textobject
omap id <Plug>CamelCaseMotion_iw
xmap id <Plug>CamelCaseMotion_iw

" Alt + motions to navigate subwords
nmap ∑ <Plug>CamelCaseMotion_w
nmap ∫ <Plug>CamelCaseMotion_b

" Moving around in blocks
noremap K {
noremap J }
noremap H ^
noremap L $

" Deleting to start/end of paragraph
nn dK dV{
nn dJ dV}

" Navigating windows
noremap <C-h> <C-W>h
noremap <C-l> <C-W>l
noremap <C-j> <C-W>j
noremap <C-k> <C-W>k

" Surround keymaps
let g:sandwich_no_default_key_mappings = 1
silent! nmap <unique><silent> dS <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
silent! nmap <unique><silent> cS <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
silent! nmap <unique><silent> ds <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
silent! nmap <unique><silent> cs <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)

let g:operator_sandwich_no_default_key_mappings = 1
" add
silent! map <unique> ys <Plug>(operator-sandwich-add)
" delete
silent! xmap <unique> ds <Plug>(operator-sandwich-delete)
" replace
silent! xmap <unique> cs <Plug>(operator-sandwich-replace)

runtime autoload/repeat.vim
if hasmapto('<Plug>(RepeatDot)')
  nmap . <Plug>(operator-sandwich-predot)<Plug>(RepeatDot)
else
  nmap . <Plug>(operator-sandwich-dot)
endif

" Open file vertically to the right
augroup netrw_mappings
    autocmd!
    autocmd filetype netrw call Netrw_mappings()
augroup END
function! OpenToRight()
  :rightbelow vnew
  :wincmd p
  :normal P
endfunction
function! Netrw_mappings()
    noremap V :call OpenToRight()<cr>
endfunction

" coc.nvim config
autocmd FileType json syntax match Comment +\/\/.\+$+

set updatetime=300

nmap <silent> gd <Plug>(coc-definition)
</details>

**Comment by chemzqm** [comment]
Profile your vim, it's not likely issue of this extension.

**Comment by DomKennedy** [comment]
Turns out the slowdown was caused by the mapping `silent! map <unique> ys <Plug>(operator-sandwich-add)`. Specifically, the mapping being active in `operator-pending` presumably caused some kind of delay to see if `yy` would turn into `yys`. 

Changing to `nmap` fixed the problem, which I should really have been using from the beginning given that the relevant operator doesn't make sense in `operator-pending` anyway.
