### ISSUE TITLE
space  + y created two windows

### ISSUE THREAD

**Issue by 0x8f701** [neoclide/coc-yank#24]
![image](https://user-images.githubusercontent.com/33961674/85228140-ef2def80-b3e1-11ea-9cac-b9fa79619666.png)

As you can see there are two windows, which are very confusing:

- .vimrc --- preview yank place
- scratch --- yank history

it's good to have preview window but it's really not useful...and it makes it strange to switch between windows...normally we would like to switch between workspace and yank history.

**Comment by 0x8f701** [comment]
BTW there is also an extra `line` word, I'm wondering why do we need it

**Comment by chemzqm** [comment]
You have `--auto-preview` for `list.source.yank.defaultOptions` configuration.

**Comment by 0x8f701** [comment]
hi @chemzqm thanks it works. How about the `line` word, it's confusing to me.

Will just number be better?


![image](https://user-images.githubusercontent.com/33961674/85422149-8d05f380-b575-11ea-80a0-31a92c5e9193.png)

From the image you can see they all have prefix: `line`, which makes me have the feeling that `line` is also part of the yanked line.

Because there isn't any seperator, I think a number will be better or just nothing

Is there already a configuration for this?

**Comment by chemzqm** [comment]
No, PR welcome.
