### ISSUE TITLE
Yank Highlighting does not dissappear if you switch buffers

### ISSUE THREAD

**Issue by AtomToast** [neoclide/coc-yank#25]
I often copy one thing from one window to another and thus do a yank and then a quick switch over. However in that case the highlighting of the yank does not disappear anymore and stays around until I close that window and reopen it. Even if the yanked lines are deleted.
This visually breaks the file quite badly

**Comment by fffed** [comment]
I have the same issue (neovim 0.4.4). Looks like recently added `winid` is the sourse of it: [add winid for coc#util#clearmatches](https://github.com/neoclide/coc-yank/commit/96e6a70633eb43a52d9e3cdb633fcf0ed9c746a9)

**Comment by chemzqm** [comment]
Use `autocmd WinLeave * call coc#util#clear_pos_matches('^HighlightedyankRegion')`

**Comment by AtomToast** [comment]
This does indeed solve the problem though I feel like this shouldn't be a hack everyone would need to apply themselves but should rather be solved on the level of coc-yank
