### ISSUE TITLE
The yank completions are problematic…

### ISSUE THREAD

**Issue by psprint** [neoclide/coc-yank#27]
…because they are *long*… Because of this they push out the completion popup leaving almost no space for the additional-information popup (`completeopt+=popup`)… E.g.:
![2020-09-28-061722_1919x745_scrot](https://user-images.githubusercontent.com/6049288/94390405-d789a400-0152-11eb-93ed-e6044bb33622.png)

Therefore, is there / or could be implemented — an option to shorten the complete candidates' texts? I'm not sure if this wouldn't cause truncated-yanks to be inserted / completed, but maybe there's a way around this?

Or maybe add an option to exclude yanks longer than <N> characters?

**Comment by chemzqm** [comment]
`:h coc-config-suggest`
