### ISSUE TITLE
Yank highlight is stuck

### ISSUE THREAD

**Issue by carloscoves** [neoclide/coc-yank#29]
The hightlight is permanent sometimes, specially on line yank

![image](https://user-images.githubusercontent.com/68688482/95042491-5db96380-06da-11eb-85e4-362f1dcbaaff.png)

I have to close the buffer to reset it.

**Comment by chemzqm** [comment]
Looks like you need upgrade your vim to support clear matches of other window.

**Comment by carloscoves** [comment]
Still happening after upgrade to 0.4.4
