### ISSUE TITLE
highlights wrong lines

### ISSUE THREAD

**Issue by DZ84** [neoclide/coc-yank#38]
vim version: VIM - Vi IMproved 9.0 9001182
node version: v19.6.0
coc.nvim version: 0.0.82-f9bfe5dc 2022-11-25 05:42:48 +0800
term: dumb
platform: linux

coc-yank: 1.2.1

Highlights are broken when doing shift+V then moving up or down and then deselecting with ctrl+[

Highlights work fine when yanking with y10j or y10k or 4yy.

The yanked selection itself is fine.

**Comment by chemzqm** [comment]
Fixed by #39
