### ISSUE TITLE
Paste mode is not exited after exiting yank list

### ISSUE THREAD

**Issue by daquexian** [neoclide/coc-yank#4]
Step:

1. :CocList -A --normal yank<cr>
2. Esc

The paste mode is not exited

**Comment by daquexian** [comment]
CocInfo:

> ## versions
> 
> vim version: NVIM v0.4.0-495-gf793c578b
> node version: v11.14.0
> coc.nvim version: 0.0.67-727982667e
> term: screen-256color
> platform: linux

**Comment by chemzqm** [comment]
This extension doesn't set paste for you, checkout your other plugins.
